name: UI tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ui:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ui_test_engine: [chrome, firefox]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: IKT_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby 3.1.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true

      - name: Setup Database
        run: |
          bundle exec rails db:create
          bundle exec rails db:schema:load
        env:
          RAILS_ENV: test
          DATABASE_URL: "postgresql://postgres:postgres@localhost/IKT_test"

      - name: Run RSpec tests (UI group)
        run: bundle exec rspec --tag ui
        env:
          RAILS_ENV: test
          SMTP_FROM: test@ikt.capybara
          DATABASE_URL: "postgresql://postgres:postgres@localhost/IKT_test"
          UI_TEST_ENGINE: ${{ matrix.ui_test_engine }}
